<?php if ($block->isEnable()) : ?>
    <?php if ($block->isThisPageEnable() && $block->isThisPositionEnable()) : ?>
        <style type="text/css">
            .a2a_svg, .a2a_count {
                border-radius: <?=$block->getBorderRadius()?> !important;
            }
			.mbMobileDevice{
				display:none;
			}
            <?php if ($block->isDisplayInline()) :?>
            .mbSocialShareInline, .mbSocialShareInlineUnderCart {
                display: flex;
                padding-bottom: 15px;
            }

            .mbSocialShareInline {
                justify-content: flex-end;
            }
            .mbSocialShareInlineUnderCart {
                justify-content: flex-start;
            }
            <?php else : ?>
            .mbSocialShareFloat {
            <?php if ($block->isVerticalStyle($block->getFloatStyle())) : ?><?=$block->getFloatMargin("top")?><?php endif;?><?=$block->getFloatPosition()?><? $block->getBackgroundColor()?> 
			z-index: 10;
            }
            @media only screen and (min-width: 430px) {
                .navigation {
                    z-index: 1;
                }
            }
            .footer-bottom .container .logo {
                z-index: 0;
            }			
            <?php if (!$block->isVerticalStyle($block->getFloatStyle())) :?>
            .a2a_floating_style.a2a_default_style {
            <?=$block->getFloatMargin("bottom")?>
            }
            <?php endif;?>
            <?php endif;?>
        </style>

		<?php $buttonSize = $block->getButtonSize(); ?>
		
        <div class="<?= $block->getContainerClass($block->getDisplayType()) ?>">
            <div class="a2a_kit <?= $block->getDisplayType() ?> <?= $buttonSize ?> <?= $block->getFloatStyle() ?> mbDesktopDevice">
			
                <?php foreach ($block->getEnableService() as $enableService) : ?>
                    <?php if ($block->isImageEnable($enableService)) : ?>
                        <a class="a2a_button_<?= $enableService ?> <?= $block->getShareCounter() ?>">
                            <img src="<?= $block->getImageUrl($enableService) ?>" <?= $block->setImageSize($buttonSize) ?> alt="<?= $enableService ?>">
                        </a>
                    <?php else : ?>
                        <a class="a2a_button_<?= $enableService ?> <?= $block->getShareCounter() ?>"></a>
                    <?php endif; ?>
                <?php endforeach; ?>

                <?php if ($block->isAddMoreShare()) : ?>
                    <a class="a2a_dd <?= $block->getShareCounter() ?>" href="https://www.addtoany.com/share"></a>
                <?php endif; ?>
            </div>
        </div>
		
		<?php if($block->getDeviceMaxWidth() != ""){ ?>
		
		<?php $buttonSize = $block->getFlotMobileButtonSize(); ?>
		
		<div class="<?= $block->getContainerClass($block->getDisplayType()) ?>">
            <div class="a2a_kit <?= $block->getDisplayType() ?> <?= $buttonSize ?> <?= $block->getFloatStyle() ?> mbMobileDevice">
			
                <?php foreach ($block->getEnableService() as $enableService) : ?>
                    <?php if ($block->isImageEnable($enableService)) : ?>
                        <a class="a2a_button_<?= $enableService ?> <?= $block->getShareCounter() ?>">
                            <img src="<?= $block->getImageUrl($enableService) ?>" <?= $block->setImageSize($buttonSize) ?> alt="<?= $enableService ?>">
                        </a>
                    <?php else : ?>
                        <a class="a2a_button_<?= $enableService ?> <?= $block->getShareCounter() ?>"></a>
                    <?php endif; ?>
                <?php endforeach; ?>

                <?php if ($block->isAddMoreShare()) : ?>
                    <a class="a2a_dd <?= $block->getShareCounter() ?>" href="https://www.addtoany.com/share"></a>
                <?php endif; ?>
            </div>
        </div>
		<?php } ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magebees_Socialsharing/js/mbconfig": {
                    "buttonColor": "<?= $block->getButtonColor() ?>",
                    "iconColor": "<?= $block->getIconColor() ?>",
                    "click": "<?= $block->getMenuType() ?>",
                    "popUp": "<?= $block->getThankYou() ?>",
                    "service": "<?= $block->getNumberOfService() ?>",
                    "disable": "<?= $block->getDisabledServices() ?>"
                }
            }
        }
        </script>
		<script>
			require([
				'jquery',
				'Magento_Ui/js/modal/modal'
				],
				function($,modal) {
					iconchange();
					$(window).resize(function() {
						iconchange();
					});
					function iconchange(){
						<?php if($block->getDeviceMaxWidth() != ""){ ?>
						if($(window).width() < <?php echo $block->getDeviceMaxWidth() ?>){
							<?php if($block->getHideondevice() == 1){ ?>
								$(".mbDesktopDevice").hide();
								$(".mbMobileDevice").hide();
							<?php }else{ ?>
								$(".mbDesktopDevice").hide();
								$(".mbMobileDevice").show();
							<?php } ?>
						}else{
							$(".mbDesktopDevice").show();
							$(".mbMobileDevice").hide();
						}
						<?php } ?>
					}
				}
			);
		</script>
    <?php endif; ?>
<?php endif; ?>