<?php
	if($this->getData('ProductCount')){
		$productCount = $this->getData('ProductCount');
	}else{
		$productCount = 5;
	}
   
	$helper = $block->getHelper();	
	$type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';	
	$items = $block->getProductCollection()->setOrder('entity_id', 'asc');
	$items->clear();
    $items->setPageSize($productCount);	
	$items ->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
 <style>
.cs-showmore{
	 text-align: center;
}

.cs-showmore a{
    background: #eee none repeat scroll 0 0;
    border: 1px solid #ccc;
	border-radius: 5px;
    box-sizing: border-box;
    color: #333;
    cursor: pointer;
    display: inline-block;
    font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 1.4rem;
    font-weight: 600;
    line-height: 1.6rem;
    margin: 0;
    padding: 10px 20px;
    vertical-align: middle;
}

.page-layout-1column .block.widget .mcs-csproduct-list .product-item {
    width: 16.4%;
}
</style> 

<div class="block widget block-products-list <?php  /* @noEscape */ echo $mode; ?>">
        
        

        <div class="block-content">
            <?php  /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
			
            <div class="products-<?php  /* @noEscape */ echo $mode; ?> <?php  /* @noEscape */ echo $mode; ?>">
			
                 <ul class="product-items <?php  /* @noEscape */ echo $type; ?> mcs-csproduct-list">
                    <?php $iterator = 1; ?>
                    <?php $setColumn = 10 ?>
                    <?php $ct = 0; ?>
                    <?php $count = count($items)+1; ?>
                    <?php foreach ($items as $_item) : ?>
                    <?php  $ct++;?>
                        <?php  /* @noEscape */ echo($iterator++ == 1) ? '<li class="product-item">' :
                        '</li>
						<li class="product-item">' ?>
                        <div class="slide">
                            <a href="<?php  /* @noEscape */ echo $block->getProductUrl($_item) ?>"
                            class="product-item-photo">
                                <?php  /* @noEscape */ echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php  /* @noEscape */ echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php  /* @noEscape */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php  /* @noEscape */ echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                               
                                    echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType) : ?>
                                    <?php  /* @noEscape */ echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
												
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
												
												
                                                    <?php //if ($block->getFeaturedprodDisplayAd2Cart()) {?>
                                                        <button class="action tocart primary"
                                                            data-mage-init='{"redirectUrl":{"url":"
                                                            <?php  /* @noEscape */ echo $block->
                                                            getAddToCartUrl($_item) ?>"}}'
                                                            type="button"
                                                            title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                            <span>
                                                                <?php  /* @noEscape */ echo __('Add to Cart') ?>
                                                            </span>
                                                        </button>
                                                    <?php //}?>
													
                                                    <?php else : ?>
                                                        <?php
                                                            $postDataHelper = $this->helper(
                                                                'Magento\Framework\Data\Helper\PostHelper'
                                                            );
                                                            $postData = $postDataHelper->getPostData(
                                                                $block->getAddToCartUrl($_item),
                                                                [
                                                                'product' => $_item->getEntityId()
                                                                ]
                                                            )
                                                        ?>
                                                        <?php //if ($block->getFeaturedprodDisplayAd2Cart()) {?>
														
                                                        <button class="action tocart primary"
                                                                data-post='<?php  /* @noEscape */ echo $postData; ?>'
                                                                type="button"
                                                                title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                            <span>
                                                                <?php  /* @noEscape */ echo __('Add to Cart') ?>
                                                            </span>
                                                        </button>
																											
                                                        <?php //}?>
                                                    <?php endif; ?>
													
													
													
													
                                                <?php else : ?>
                                                    <?php if ($_item->getIsSalable()) : ?>
                                                        <div class="stock available">
                                                            <span><?php  /* @noEscape */ echo __('In stock') ?></span>
                                                        </div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable">
                                                            <span>
                                                                <?php  /* @noEscape */ echo __('Out of stock') ?>
                                                            </span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                            <?php // if ($block->getFeaturedprodDisplayAd2Wishlist()) {?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->
                                                isAllow() && $showWishlist
                                                    ) : ?>
                                                    <a href="#"
                                                       data-post='<?php  /* @noEscape */ echo $block->
                                                        getAddToWishlistParams($_item); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php  /* @noEscape */ echo __('Add to Wish List') ?>">
                                                        <span>
                                                            <?php  /* @noEscape */ echo __('Add to Wish List') ?>
                                                        </span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php //}?>
											
                                            <?php //if ($block->getFeaturedprodDisplayAd2Compare()) {?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                    <?php
                                                        $compareHelper = $this->helper(
                                                            'Magento\Catalog\Helper\Product\Compare'
                                                        );
                                                    ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php
                                                        /* @noEscape */ echo $compareHelper->getPostDataParams($_item);
                                                        ?>'
                                                       title="<?php  /* @noEscape */ echo __('Add to Compare') ?>">
                                                        <span><?php  /* @noEscape */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php //}?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php  /* @noEscape */ echo($iterator == $count) ? '</li>' : '' ?>                        
                       
                    <?php endforeach ?>
                </ul>
            </div>            
        </div>	
		
		<div class="cs-showmore">
			<a href="<?php echo $block->getShowMoreLink(); ?>">Show More</a>
		</div>
		
    </div>
