<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AttrBaseSplitcart
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/**  @var $block \Webkul\AttrBaseSplitcart\Block\Index */
?>
<?php
$splitBlock = $block->getLayout()->createBlock(
    'Webkul\AttrBaseSplitcart\Block\Index'
);
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>

<?php
if ($splitBlock->getAttributesplitcartEnable()) {
    $cartData = $splitBlock->getCartDataByAttribute();
    foreach ($cartData as $attrValueId => $cartItem) {
?>
<div class="split-details">
    <span>
        <strong><?php /* @noEscape */ echo __($cartItem['attr_detail']['label'])." :-"?></strong>
    </span>
    <span>
        <?php /* @noEscape */ echo __($cartItem['attr_detail']['value']);?>
    </span>
</div>
<form action="<?php /* @noEscape */ echo $block->getUrl('checkout/cart/updatePost') ?>"
        method="post"
        id="form-validate-<?php /* @noEscape */ echo $attrValueId;?>"
        data-mage-init='{"validation":{}}'
        class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="wk-mpsplit-wrapper">
        <div class="cart table-wrapper<?php /* @noEscape */ echo $mergedCells == 2 ? ' detailed' : ''; ?>">
            <table id="shopping-cart-table-<?php /* @noEscape */ echo $attrValueId;?>"
                   class="cart items data table"
                   data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
                   "updateCartActionContainer": "#update_cart_action_container"}}'>
                <caption role="heading" aria-level="2" class="table-caption">
                    <?php /* @noEscape */ echo __('Shopping Cart Items') ?>
                </caption>
                <thead>
                    <tr>
                        <th class="col item" scope="col">
                            <span>
                                <?php /* @noEscape */ echo __('Item') ?>
                            </span>
                        </th>
                        <th class="col price" scope="col">
                            <span>
                                <?php /* @noEscape */ echo __('Price') ?>
                            </span>
                        </th>
                        <th class="col qty" scope="col">
                            <span>
                                <?php /* @noEscape */ echo __('Qty') ?>
                            </span>
                        </th>
                        <th class="col subtotal" scope="col">
                            <span>
                                <?php /* @noEscape */ echo __('Subtotal') ?>
                            </span>
                        </th>
                    </tr>
                </thead>
                <?php foreach ($block->getItems() as $_item) :?>
                    <?php if (array_key_exists($_item->getId(), $cartItem)) : ?>
                        <?php echo $block->getItemHtml($_item) ?>
                    <?php endif; ?>
                <?php endforeach ?>
            </table>
        </div>
        <div class="cart main actions">
            <?php if ($block->getContinueShoppingUrl()) : ?>
                <a class="action continue"
                   href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
                   title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                    <span>
                        <?php /* @noEscape */ echo __('Continue Shopping') ?>
                    </span>
                </a>
            <?php endif; ?>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?php /* @noEscape */ echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                    class="action clear" id="empty_cart_button-<?php /* @noEscape */ echo $attrValueId;?>">
                <span>
                    <?php /* @noEscape */ echo __('Clear Shopping Cart'); ?>
                </span>
            </button>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-item-update=""
                    value="update_qty"
                    title="<?php /* @noEscape */ echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                    class="action update">
                <span>
                    <?php /* @noEscape */ echo __('Update Shopping Cart'); ?>
                </span>
            </button>
            <input type="hidden"
                    value=""
                    id="update_cart_action_container-<?php /* @noEscape */ echo $attrValueId;?>"
                    data-cart-item-update=""/>
        </div>
    </div>
</form>

<form action="<?php /* @noEscape */ echo $block->getUrl('attrbasesplitcart/cartover/proceedtocheckout') ?>"
            method="post"
            id="checkout-validate-<?php /* @noEscape */ echo $attrValueId;?>"
            data-mage-init='{"validation":{}}'
            class="form form-checkout">
            <?php echo $block->getBlockHtml('formkey'); ?>
        <div class="cart-summary">
            <input type="hidden"
                    name="attrsplitcart_attribute"
                    class="wk-attr-id"
                    value="<?php /* @noEscape */ echo $splitBlock->getSelectedAttribute(); ?>">
            <div data-bind="scope:'giftOptionsCart'" id="gift-options-cart"></div>
            <div class="cart-summary1">
                <strong class="summary title"><?php /* @noEscape */ echo __("Summary")?></strong>
                <div data-bind="scope:'block-totals'"
                        class="cart-totals"
                        id="cart-totals-<?php /* @noEscape */ echo $attrValueId;?>">
                    <div data-bind="blockLoader: isLoading" class="table-wrapper">
                        <table class="data table totals">
                            <caption class="table-caption"><?php /* @noEscape */ echo __("Total")?></caption>
                            <tbody>
                                <tr class="totals sub">
                                    <th scope="row" colspan="1" class="mark">
                                        <?php /* @noEscape */ echo __("Subtotal")?>
                                    </th>
                                    <td data-th="Subtotal" class="amount">
                                        <span class="price">
                                            <?php /* @noEscape */ echo $cartItem['formatted_total']; ?>
                                        </span>
                                    </td>
                                </tr>
                                <tr class="grand totals">
                                    <th scope="row" colspan="1" class="mark">
                                        <strong data-bind="text: title">
                                            <?php /* @noEscape */ echo __("Order Total")?>
                                        </strong>
                                    </th>
                                    <td data-th="Order Total" class="amount">
                                        <strong>
                                            <span class="price">
                                                <?php /* @noEscape */ echo $cartItem['formatted_total']; ?>
                                            </span>
                                        </strong>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <ul class="checkout methods items checkout-methods-items">
                    <li class="item">
                        <button class="action primary checkout mp-btn-checkout"
                                title="Go to Checkout"
                                data-role="proceed-to-checkout"
                                type="submit"
                                value='<?php /* @noEscape */ echo $attrValueId ?>'
                                name="attrsplitcart_value">
                            <span><?php /* @noEscape */ echo __("Go to Checkout")?></span>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </form>
<?php
    }
}?>
<?php /* @noEscape */ echo $block->getChildHtml('shopping.cart.table.after'); ?>
<?php $shippingBlock = $block->getLayout()->createBlock(
    'Magento\Checkout\Block\Cart\Shipping'
); ?>
<script text="x-magento-init">
    window.checkoutConfig = <?php /* @noEscape */ echo \Zend_Json::encode(
        $shippingBlock->getCheckoutConfig()
    );?>;
</script>
<?php $giftOptionsBlock = $block->getLayout()->createBlock(
    'Magento\GiftMessage\Block\Cart\GiftOptions'
); ?>
<script text="x-magento-init">
    window.giftOptionsConfig = <?php /* @noEscape */ echo $giftOptionsBlock->getGiftOptionsConfigJson(); ?>;
</script>
