<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Theme\Block\Html\Footer $block */
?>
<small class="copyright">
    <img class="footer-cimg" style="display:none;width:9%;padding:0px 15px;" src="<?= $block->getViewFileUrl('images/footer/footerllogo.png'); ?>">
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
</small>
