<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>
<?php if ($block->isProductVisibleInSiteVisibility()) :?>
    <a class="action action-edit"
       href="<?= $block->escapeUrl($block->getConfigureUrl()) ?>"
       title="<?= $block->escapeHtmlAttr(__('Edit item parameters')) ?>">
        <img class="rem-cart" src="<?php echo $baseUrl; ?>pub/media/footer/icon-pencil.png">
    </a>
<?php endif ?>
