<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()) :?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                class="action primary customize print-bundle"
                type="button">
            <span><?= $block->escapeHtml(__('Customize')) ?></span>
        </button>
    </div>
<?php endif;?>
